version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.10.1
    working_directory: ~/app
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - restore_cache:
          keys:
          - til-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - til-

      - run:
          name: install-npm-wee
          command: npm install
      - run:
          name: install-hexo
          command: 'sudo npm install hexo-cli -g'
      - save_cache:
          paths:
            - node_modules
          key: til-{{ checksum "package.json" }}     
      - run: git config --global user.name "Circle CI"
      - run: git config --global user.email "deduce@gmail.com"
      - run: hexo clean
      - run: hexo generate
      - run: hexo deploy
      - run: bin/automated
